stacklok/toolhive-studio

main/src/auto-launch.ts
main/src/graceful-exit.ts
main/src/logger.ts
main/src/main.ts
main/src/menu.ts
main/src/system-tray.ts
main/src/toolhive-manager.ts
package.json
pnpm-lock.yaml
renderer/src/common/components/error/connection-refused-error.tsx
renderer/src/features/registry-servers/components/grid-cards-registry-server.tsx
renderer/src/renderer.tsx
renderer/src/routes/__root.tsx
utils/constants.ts
vitest.setup.ts

Used [electron-log](https://github.com/megahertz/electron-log) replacing `console` with `log` fn.
The log will be saved into the filesystem:
- on Linux: ~/.config/{app name}/logs/main.log
- on macOS: ~/Library/Logs/{app name}/main.log
- on Windows: %USERPROFILE%\AppData\Roaming\{app name}\logs\main.log
___
nit: we can improve or replace later, but we got some issues using directly the dmg download from github repo, that we cannot reproduce locally, so it would helpful to have some additional info here.
`Logs with info|warn|error`
`Logs in both thv serve and logs file`

chore(log): add electron-log in order to troubleshooting issues

---

README.md
renderer/src/features/mcp-servers/components/__tests__/dialog-form-run-mcp-command.test.tsx
renderer/src/features/mcp-servers/components/dialog-form-run-mcp-command.tsx
renderer/src/features/mcp-servers/components/form-fields-run-mcp-command.tsx
renderer/src/features/registry-servers/components/__tests__/form-run-from-registry.test.tsx
renderer/src/features/registry-servers/components/form-run-from-registry.tsx
renderer/src/features/secrets/components/__tests__/dialog-form-secret.test.tsx
renderer/src/features/secrets/components/dialog-form-secret.tsx
renderer/src/routes/__tests__/registry.test.tsx
renderer/src/routes/secrets.tsx

Some small updates to labels:
* Fixed some capitalization inconsistencies
* Made the custom server submission button label consistent with adding from registry ("Install server", not "Submit")
* Added `:latest` / `@latest` to example image/package inputs
* On the update secret modal, updated some strings that didn't sound right to me:
* "Replacement secret" -> "New value"
* "Secret contents" -> "Secret value

fix: minor label consistency and wording updates

---

renderer/src/common/components/ui/alert.tsx
renderer/src/features/registry-servers/components/__tests__/form-run-from-registry.test.tsx
renderer/src/features/registry-servers/components/alert-error-form-submission.tsx
renderer/src/features/registry-servers/components/form-run-from-registry.tsx
renderer/src/features/registry-servers/components/grid-cards-registry-server.tsx
renderer/src/features/registry-servers/components/loading-state-alert.tsx
renderer/src/features/registry-servers/hooks/use-run-from-registry.tsx
renderer/src/features/registry-servers/lib/__tests__/orchestrate-run-registry-server.test.tsx
renderer/src/features/registry-servers/lib/orchestrate-run-registry-server.tsx
renderer/src/routes/registry.tsx

This is moving from toast only messages to inline form, that handle the possible errors directly on the submit of the form
new flow:
https://github.com/user-attachments/assets/172795b1-ba5a-435f-ae2e-996a833ac713
fine tunned error:

feat(registry): improve registry install form

---

CONTRIBUTING.md
README.md
docs/README.md
forge.config.ts
main/src/auto-launch.ts
main/src/system-tray.ts
main/src/tests/auto-launch.test.ts
package.json
renderer/index.html
renderer/src/common/components/error/__tests__/index.test.tsx
renderer/src/common/components/error/connection-refused-error.tsx
renderer/src/common/components/error/keyring-error.tsx
renderer/src/common/hooks/use-confirm-quit.ts

We decided to refactor the name from ToolHive Studio to ToolHive, having product consistency with the CLI

chore: refactor app name

---

renderer/src/features/clients/components/card-client.tsx

Minor nitpick, the proper name is "VS Code Insiders" (internally thv uses just "insider" but MS pluralizes it)

fix: correct VS Code Insiders label

---

README.md
renderer/src/common/components/help/help-dropdown.tsx

Add privacy policy link to settings menu. Update readme with the Sentry section

chore: add privacy policy link and update readme

---

renderer/src/features/secrets/components/dialog-form-secret.tsx
renderer/src/routes/__tests__/secrets.test.tsx

note: the description is an accessibility requirement for screen readers and our tests will fail without it, because radix ui issues console warnings for it, and we fail our tests on console warnings.
this behavior makes sense, so instead of disabling it, I decided to keep the description for screen readers (hence the sr-only class).
In order to make the behavior less confusing when refactoring/debugging this area of the app, I also added a test case that verifies the screen-reader behavior.
fixes: https://github.com/stacklok/toolhive-studio/issues/468

feat: remove excessive description from "Add a secret" dialog

---

renderer/src/common/components/ui/form.tsx
renderer/src/features/secrets/components/dialog-form-secret.tsx
renderer/src/routes/__tests__/secrets.test.tsx

feat: display secret name when editing it

---

main/src/main.ts
main/src/toolhive-manager.ts

When we auto-update, we are not waiting for graceful exit completed to stop all the containers and we are not showing any feedback.
Adding await on `stopAllServers` should fix this issue

fix: wait graceful exit before quit and install new version

---

renderer/src/features/registry-servers/components/__tests__/form-run-from-registry.test.tsx
renderer/src/features/registry-servers/components/form-run-from-registry/network-isolation-tab-content.tsx

Updating the label on the network isolation toggle switch to "Enable outbound network filtering" for clarity.
Aligns with the [design](https://www.figma.com/design/KuQGsgrNzRCGmSTl520Hwh/Toolhive-Desktop?node-id=2379-14621&t=3JO9gnfu9XQyDgHW-4).
Also updated the "Allowed hosts"/"Allowed ports" labels to sentence case to match other input box labels around the app.

fix: update network isolation labels

---

renderer/src/common/components/ui/tooltip-info-icon.tsx
renderer/src/features/registry-servers/components/__tests__/form-run-from-registry.test.tsx
renderer/src/features/registry-servers/components/form-run-from-registry/configuration-tab-content.tsx

feat(registry): show tooltip for secrets and env var

---

main/src/container-engine.ts

Add an extra error log when the container engine command fails

chore: add log for failing check command

---

renderer/src/common/hooks/use-toast-mutation.ts
renderer/src/features/mcp-servers/hooks/__tests__/use-mutation-restart-server.test.ts
renderer/src/features/mcp-servers/hooks/use-mutation-restart-server.ts
renderer/src/routes/__tests__/index.test.tsx

Enhanced the useMutationRestartServerAtStartup hook to automatically dismiss the restart servers toast when a server shutdown event occurs.
**Key Improvements**
- Toast ID Management: Added dedicated TOAST_ID constant ('restart-servers-startup') for consistent toast identification
- Automatic Cleanup: Implemented onServerShutdown event listener to dismiss active restart toast when servers are shut down
- Better UX: Prevents lingering "Restarting servers..." notifications when the application or servers are being shut down
https://github.com/user-attachments/assets/f2913763-26d6-4670-ae8d-78e361e3f06f

fix: dismiss toast in case of shutting down

---

renderer/src/features/mcp-servers/components/__tests__/dialog-form-run-mcp-command.test.tsx
renderer/src/features/mcp-servers/components/__tests__/network-isolation-tab-content.test.tsx
renderer/src/features/mcp-servers/components/network-isolation-tab-content.tsx
renderer/src/features/mcp-servers/lib/__tests__/orchestrate-run-custom-server.test.tsx
renderer/src/features/mcp-servers/lib/form-schema-run-mcp-server-with-command.ts
renderer/src/features/mcp-servers/lib/orchestrate-run-custom-server.tsx
renderer/src/features/network-isolation/components/network-isolation-tab-content.tsx
renderer/src/features/registry-servers/components/__tests__/form-run-from-registry.test.tsx
renderer/src/features/registry-servers/components/dynamic-array-field.tsx
renderer/src/features/registry-servers/components/form-run-from-registry/index.tsx
renderer/src/features/registry-servers/lib/__tests__/orchestrate-run-registry-server.test.tsx
renderer/src/features/registry-servers/lib/get-form-schema-run-from-registry.ts
renderer/src/features/registry-servers/lib/orchestrate-run-registry-server.tsx

This is a wel know issue with `react-hook-form` + `zod` + `useFieldArray`
detail https://github.com/orgs/react-hook-form/discussions/9875
The only way for now to solve it is to reset the form state manually `form.reset(form.getValues())` allowing to reset from state and set as default values the current form values, so basically it is simulating that the form was initialized with the current values.
https://github.com/user-attachments/assets/8560f559-3b74-4ae9-8dc5-b4bea8e21c44

fix: form validation for host port fields

---

renovate.json

Adds a custom regex manager to Renovate configuration to automatically track ToolHive releases from `stacklok/toolhive` and update the `TOOLHIVE_VERSION` constant in `utils/constants.ts`.
Currently tracking version `v0.2.3`, will create PRs when new versions are released.

chore: configure renovate to track toolhive releases

---

renovate.json

Fixes the Renovate custom regex manager configuration to properly track ToolHive releases:
- Added `packageNameTemplate` for github-releases datasource
- Removed `versioningTemplate` (defaults to semver-coerced)
- Fixed `managerFilePatterns` to remove unnecessary regex anchors
- Set `depNameTemplate` to just "toolhive" for cleaner PR titles

fix: renovate config for toolhive tracking

---

.github/workflows/on-main.yml
.github/workflows/on-pr.yml
renderer/src/common/components/ui/tooltip.tsx
renderer/src/common/hooks/use-is-truncated.ts
renderer/src/features/mcp-servers/components/card-mcp-server.tsx

Improve the tooltip capability with `useIsTruncated` in order to show the tooltip content only in case of truncate leveraging `onlyWhenTruncated` prop when it is passed
**Before**
https://github.com/user-attachments/assets/eb0b1a69-86ae-4b2b-baff-6e5827d305e4
**After**
https://github.com/user-attachments/assets/de74f1ce-6397-4702-8de8-dc4b860c8a5b

fix: show tooltip when text is truncated

---

renovate.json

Switches Renovate configuration from tracking GitHub releases to tracking Docker container images at `ghcr.io/stacklok/toolhive`.
- Changed datasource from `github-releases` to `docker`
- Updated `depNameTemplate` to use the full Docker image path `ghcr.io/stacklok/toolhive`
- Removed unnecessary `packageNameTemplate` and `versioningTemplate`
- Added `extractVersionTemplate` to handle the `v` prefix in Docker tags
- Updated regex to handle versions with or without the `v` prefix
- Simplified `managerFilePatterns` pattern
This should properly track ToolHive Docker images which are tagged as `v0.2.5`, etc.

fix: switch renovate to track docker images instead of github releases

---

.github/workflows/mirror-to-gh-pages.yml

- Add workflow to automatically mirror release assets to GitHub Pages CDN
- Include SHA256 checksums for all assets (individual .sha256 files + SHA256SUMS.txt)
- Generate JSON manifest with asset metadata (name, url, size, sha256)
- Support latest-only deployment (/latest/) due to 1GB GitHub Pages limit
- Use Git LFS for large binary files (>100MB) to bypass file size limits
- Skip prerelease versions to only mirror stable releases
- Support manual trigger via workflow_dispatch for any release tag
- Use peaceiris/actions-gh-pages for reliable deployment
- Solves GitHub Releases rate limiting issues with dedicated CDN endpoint

ci: add GitHub Pages release assets mirror workflow

---

main/src/graceful-exit.ts
main/src/tests/graceful-exit.test.ts

This PR enhances the `graceful-exit` functionality by updating the polling logic to properly handle all final server statuses that now we have with the latest API update (stopped, error, unknown, unhealthy) instead of just checking for running servers. Added also some unit tests

feat(graceful-exit): improve with better status checking and testing

---

renderer/src/common/hooks/use-toast-mutation.ts
renderer/src/common/mocks/handlers.ts
renderer/src/features/mcp-servers/hooks/__tests__/use-mutation-restart-server.test.ts
renderer/src/features/mcp-servers/hooks/use-delete-server.ts
renderer/src/features/mcp-servers/hooks/use-mutation-restart-server.ts
renderer/src/features/mcp-servers/hooks/use-mutation-stop-server.ts
renderer/src/features/mcp-servers/hooks/use-run-custom-server.tsx
renderer/src/features/registry-servers/hooks/use-run-from-registry.tsx

as per title, status is no longer returned for the GET single workload, we now have this new endpoint that just checks that

feat: use the new status endpoint for polling

---

.github/workflows/_build-matrix.yml

as per title, we don't need the signature in PR, remove it

ci: remove window code signin in normal build

---

renderer/src/features/mcp-servers/components/__tests__/dialog-form-run-mcp-command.test.tsx
renderer/src/features/mcp-servers/components/dialog-form-run-mcp-command.tsx
renderer/src/features/mcp-servers/lib/__tests__/orchestrate-run-custom-server.test.tsx
renderer/src/features/mcp-servers/lib/form-schema-run-mcp-server-with-command.ts
renderer/src/features/mcp-servers/lib/orchestrate-run-custom-server.tsx
renderer/src/features/registry-servers/components/__tests__/form-run-from-registry.test.tsx
renderer/src/features/registry-servers/lib/get-form-schema-run-from-registry.ts
renderer/src/features/registry-servers/lib/orchestrate-run-registry-server.tsx

Currently the validation is always applied also if the network isolation is not enabled, we can skip the network isolation validation in case it is disabled.
Other fix:
- Fix fields format for `allowedHosts` and `allowedPorts` in case of empty values for both registry and custom form
- Fix custom form validation message for docker image, introducing union type 
**Registry form**
https://github.com/user-attachments/assets/13b574bc-93a4-4984-96b5-89857bed183c
**Custom form**
https://github.com/user-attachments/assets/9c8e7ef2-e4cb-4ff9-b032-caf387f9eb70

fix(network-isolation): skip hosts, ports if network isolation is not enabled

---

main/src/feature-flags.ts
renderer/src/features/mcp-servers/components/__tests__/card-mcp-server.test.tsx
renderer/src/features/mcp-servers/components/__tests__/dialog-form-run-mcp-command.test.tsx
renderer/src/features/mcp-servers/components/card-mcp-server.tsx
renderer/src/features/mcp-servers/components/dialog-form-run-mcp-command.tsx
renderer/src/features/mcp-servers/components/form-fields-array-custom-secrets.tsx
renderer/src/features/mcp-servers/components/form-fields-run-mcp-command.tsx
renderer/src/features/mcp-servers/components/grid-cards-mcp-server.tsx
renderer/src/features/mcp-servers/hooks/use-run-custom-server.tsx
renderer/src/features/mcp-servers/hooks/use-update-server.tsx
renderer/src/features/mcp-servers/lib/__tests__/form-schema-run-mcp-server-with-command.test.ts
renderer/src/features/mcp-servers/lib/__tests__/orchestrate-run-custom-server.test.tsx
renderer/src/features/mcp-servers/lib/form-schema-run-mcp-server-with-command.ts
renderer/src/features/mcp-servers/lib/orchestrate-run-custom-server.tsx
renderer/src/features/mcp-servers/sub-pages/customize-tools/page.tsx
utils/feature-flags.ts

in this PR:
- added a feature flag for editing
- adjusted the custom server form to be reused for editing
- adjusted the height of the custom form to avoid overflow
the APIs aren’t consistent enough, I’ll do a second step once the fixes are done/released
missing:
- pass the group on editing
- add optimistic updates when fetching the status while polling
- handle errors on GET so the edit form doesn’t break if the workload configuration isn’t available (edge case)

feat(feature-flag): implement editing with custom server form

---

renderer/src/features/mcp-servers/components/card-mcp-server/server-actions/items/edit-configuration-menu-item.tsx

We need to prevent default event actions triggered by the click on edit configuration
**BEFORE**
https://github.com/user-attachments/assets/50b3dfdc-b7cc-47bd-ac65-11a19bb6d542
**AFTER**
https://github.com/user-attachments/assets/47d900ff-0344-4963-b186-7ee4b8371420

fix: prevent default event avoiding close dialog on click

---

knip.ts
renderer/src/features/mcp-servers/components/remote-mcp/__tests__/dialog-form-remote-mcp.test.tsx
renderer/src/features/mcp-servers/components/remote-mcp/dialog-form-remote-mcp.tsx
renderer/src/features/mcp-servers/components/remote-mcp/form-fields-auth.tsx
renderer/src/features/mcp-servers/hooks/use-run-remote-server.tsx
renderer/src/features/mcp-servers/hooks/use-update-remote-server.tsx
renderer/src/features/mcp-servers/lib/orchestrate-run-remote-server.tsx

No UI changes in this PR.
Created a bunch of remote mcp form components, not rendering in the UI, only defined. Next PR will render the remote mcp form in the wrapper
```
export function WrapperDialogFormMcp({
serverType,
closeDialog,
serverToEdit,
}: {
serverType: { local: boolean; remote: boolean }
closeDialog: () => void
serverToEdit?: string | null
}) {
return (
<DialogFormLocalMcp
isOpen={serverType.local}
closeDialog={closeDialog}
serverToEdit={serverToEdit}
/>
)
}
```

feat: add remote mcp components

---

forge.config.ts

This change allows flatpak installs on systems that use rootless podman to work as expected. The placeholder `xdg-run` is supported by flatpak, and will be replaced by the users run director. For example, in a typical case it will resolve to `/run/user/1000/podman/podman.sock`.
For more information on the template variable you can see the [docs](https://docs.flatpak.org/en/latest/flatpak-command-reference.html#flatpak-run).
> --filesystem=FILESYSTEM
> 
>    .... FILESYSTEM can be one of: home, host, host-os, host-etc, xdg-desktop, xdg-documents, xdg-download, xdg-music, xdg-pictures, xdg-public-share, xdg-templates, xdg-videos, xdg-run, xdg-config, xdg-cache, xdg-data, an absolute path, or a homedir-relative path like ~/dir or paths relative to the xdg dirs, like xdg-download/subdir. ....

fix(flatpak): support rootless podman socket

---

main/src/chat/index.ts
main/src/chat/mcp-tools.ts
main/src/chat/settings-storage.ts
main/src/chat/streaming.ts
main/src/chat/thread-integration.ts
main/src/chat/threads-storage.ts
main/src/chat/types.ts
main/src/main.ts
package.json
pnpm-lock.yaml
preload/src/preload.ts
renderer/src/features/chat/components/chat-interface.tsx
renderer/src/features/chat/components/mcp-server-badge.tsx
renderer/src/features/chat/hooks/__tests__/use-chat-streaming.test.ts
renderer/src/features/chat/hooks/use-chat-settings.ts
renderer/src/features/chat/hooks/use-chat-streaming.ts
renderer/src/features/chat/hooks/use-thread-management.ts
renderer/src/features/chat/transport/__tests__/electron-ipc-chat-transport.test.ts
renderer/src/features/chat/transport/electron-ipc-chat-transport.ts

This is the first implementation for handling persistent threads, we will save the playground chat in the file system, it's a little bit verbose on IPC side but I will clean up in the next PR
I also adjusted the connection of the MCP tools for the remote ones
https://github.com/user-attachments/assets/c3c2e99d-b777-4e71-a0b7-f81033f27154

feat(playground): persist thread on storage and adjust tools

---

main/src/tests/toolhive-manager.test.ts
main/src/toolhive-manager.ts

- **Wrap ToolHive startup in Sentry scope** for better crash context and debugging
- **Add process exit crash reporting** with conditional logic to avoid noise:
- Report crashes when ToolHive exits unexpectedly (`fatal` severity)
- Skip reporting during normal app shutdown or restart operations
- **Enhanced debugging context** with breadcrumbs for process lifecycle and stderr output
- Uses `Sentry.withScope()` to capture startup context and process metadata
- Captures stderr output as breadcrumbs for better crash diagnosis
- Conditional reporting based on `isRestarting` flag and app quitting state

feat(toolhive-manager): add sentry on thv process exit

---

renderer/src/common/lib/workloads/remote/__tests__/form-schema-remote-mcp.test.ts
renderer/src/common/lib/workloads/remote/form-schema-remote-mcp.ts
renderer/src/features/mcp-servers/components/local-mcp/dialog-form-local-mcp.tsx
renderer/src/features/mcp-servers/components/remote-mcp/dialog-form-remote-mcp.tsx
renderer/src/features/mcp-servers/components/remote-mcp/form-fields-auth.tsx
renderer/src/features/registry-servers/components/dialog-form-remote-registry-mcp.tsx

Fix `callback_port` for remote mcp `Port must be between 1024 and 65535`.
The validation should be applied to all auth_type, but only for `auth_type: none`, that means dynbamic client registration, the field is mandatory.
Added a unit test for remote validation schema and reset form value after success form submitted.
https://github.com/user-attachments/assets/2ac1dbf6-8f5f-4a30-96b3-4dd96781e02b

fix: validate callback_port range value

---

renderer/src/common/components/link-view-transition.tsx
renderer/src/features/mcp-servers/components/__tests__/card-mcp-server.test.tsx
renderer/src/features/mcp-servers/components/card-mcp-server/index.tsx
renderer/src/features/mcp-servers/components/card-mcp-server/server-actions/index.tsx
renderer/src/features/mcp-servers/components/card-mcp-server/server-actions/items/logs-menu-item.tsx
renderer/src/features/mcp-servers/components/grid-cards-mcp-server.tsx
renderer/src/features/mcp-servers/sub-pages/logs-page/index.tsx
renderer/src/route-tree.gen.ts
renderer/src/routes/__tests__/logs.$serverName.test.tsx
renderer/src/routes/group.$groupName.tsx
renderer/src/routes/logs.$groupName.$serverName.tsx

related to #904 
This PR just replaces the hardcoded `default~ group in the back button in the logs page with the appropriate group name.
The only change visible to the user is that the back button leads to the appropriate group now. 
https://github.com/user-attachments/assets/404e2807-c453-41ad-b9ca-891dc1df7a3d

fix: make logs page "Back" button group-aware

---

renderer/src/features/mcp-servers/components/remote-mcp/dialog-form-remote-mcp.tsx
renderer/src/features/registry-servers/components/dialog-form-remote-registry-mcp.tsx
renderer/src/routes/(registry)/registry.tsx

We can direct link to the right tab in the new remote MCP docs pages.
Also corrects the destination for the custom registry error text.
Signed-off-by: Dan Barr <6922515+danbarr@users.noreply.github.com>

fix: update docs links to correct anchors

---

renderer/src/common/lib/toast.ts
renderer/src/features/chat/components/chat-input-prompt.tsx

as per title, when an error happens while attaching a file, we’ll trigger a toast error with the dedicated message
Example:

feat(playground): handle errors for prompt input attachments

---

README.md

Download page path has changed slightly with the updated website.
Signed-off-by: Dan Barr <6922515+danbarr@users.noreply.github.com>

fix(docs): update download link in README
