stacklok/toolhive-studio

utils/constants.ts
just doing a bump with the latest thv, no api change in this versions
=> feat: bump thv version

renderer/src/features/clients/components/card-client.tsx, renderer/src/routes/__tests__/clients.test.tsx
=> fix: clients renaming

CONTRIBUTING.md, README.md, SECURITY.md, docs/README.md, forge.config.ts, package.json, renderer/src/common/components/help/__tests__/help-dropdown.test.tsx, renderer/src/common/components/help/help-dropdown.tsx, renderer/src/common/mocks/fixtures/registry.ts, renderer/src/common/mocks/fixtures/servers.ts, renderer/src/features/mcp-servers/lib/__tests__/form-schema-run-mcp-server-with-command.test.ts
Renaming all the occurrences from stacklokLabs to stacklok org
=> chore: rename from stacklokLabs to stacklok org

main/src/main.ts, main/src/system-tray.ts, main/src/util.ts, preload/src/preload.ts, renderer/src/routes/__root.tsx
=> feat: show current version in tray

main/src/graceful-exit.ts, main/src/main.ts, main/src/system-tray.ts, main/src/util.ts, renderer/src/common/components/layout/top-nav/window-controls.tsx
https://github.com/user-attachments/assets/33f2bfdb-a2bf-4da5-81d7-b752956e0791
=> fix: quit will always trigger graceful-exit

renderer/src/features/registry-servers/components/grid-cards-registry-server.tsx, renderer/src/routes/__tests__/registry.test.tsx
=> feat: hide "filesystem" MCP temporarily

main/src/graceful-exit.ts, main/src/main.ts, main/src/util.ts, renderer/src/common/components/secrets/form-combobox-secrets-store.tsx, renderer/src/common/lib/polling.ts, utils/delay.ts
https://github.com/user-attachments/assets/863225d6-78d4-4001-bc3e-c4b9e732b646
=> fix: close popover after value selected

renderer/src/common/components/empty-state.tsx, renderer/src/common/components/title-page.tsx, renderer/src/features/secrets/components/secrets-table.tsx, renderer/src/routes/(registry)/registry.tsx, renderer/src/routes/clients.tsx, renderer/src/routes/index.tsx, renderer/src/routes/secrets.tsx
Remove sorting on secrets table. Replace all title pages font, created a shared title page component
=> fix: replace font, and remove sorting secrets table

renderer/src/features/registry-servers/lib/__tests__/orchestrate-run-registry-server.test.tsx, renderer/src/features/registry-servers/lib/orchestrate-run-registry-server.tsx
fixes https://github.com/stacklok/toolhive-studio/issues/526
=> fix: send network isolation flag

renderer/src/features/registry-servers/components/dynamic-array-field.tsx, renderer/src/features/registry-servers/components/form-run-from-registry/network-isolation-tab-content.tsx
=> fix: show tooltip on allowed host input field

renderer/src/features/registry-servers/components/form-run-from-registry/index.tsx
We can pre-fill the network isolation with the default configuration.
Reset tab after submit or cancel actions
**Pre-filled configuration**
https://github.com/user-attachments/assets/d8155edb-7484-4de5-8adf-32b878b776bd
**Custom config**
https://github.com/user-attachments/assets/12c8bdca-52e0-4796-8f08-1ac8b70bd5d4
=> feat: pre-fill the default network isolation config

README.md
fixes https://github.com/stacklok/toolhive-studio/issues/563
=> docs: remove dot from note in readme

renderer/src/common/lib/utils.ts, renderer/src/features/mcp-servers/lib/__tests__/orchestrate-run-custom-server.test.tsx, renderer/src/features/mcp-servers/lib/orchestrate-run-custom-server.tsx, renderer/src/features/registry-servers/components/__tests__/form-run-from-registry.test.tsx, renderer/src/features/registry-servers/lib/__tests__/orchestrate-run-registry-server.test.tsx, renderer/src/features/registry-servers/lib/get-form-schema-run-from-registry.ts, renderer/src/features/registry-servers/lib/orchestrate-run-registry-server.tsx
fixes https://github.com/stacklok/toolhive-studio/issues/611
=> fix: omit optional env vars when they are left empty

main/src/container-engine.ts, preload/src/preload.ts, renderer/src/common/components/error/connection-refused-error.tsx
Enhanced Container Engine Detection with Rancher Desktop Support
We had a problem where we had a packaged app failures: ENOENT errors in built Electron apps due to limited PATH, so I refactored a little bit the container engine sections and extend with Rancher Desktop that we should support now
https://github.com/user-attachments/assets/c049c517-1238-4d1d-a5bd-01ccf3eccdd1
=> feat(main): fix and extend container engine check with rancher desktop dockerd

eslint.config.mjs, tsconfig.json
just a simple format that adjust base tsconfig json and eslint config
=> chore: run format on eslint and tsconfig

renderer/src/features/registry-servers/components/grid-cards-registry-server.tsx
context for the future https://stacklok.slack.com/archives/C091GRYAG49/p1753890498281769
=> feat: temporarily hide the 'sqlite' MCP server

api/generated/@tanstack/react-query.gen.ts, api/generated/sdk.gen.ts, api/generated/types.gen.ts, api/openapi.json, utils/constants.ts
As per title, bumped the THV version and regenerated the API
=> feat: bump thv version 0.2.2

api/generated/types.gen.ts, api/openapi.json, utils/constants.ts
As per title, this is updates thv to the latest version and regenerates API
=> chore: bump thv version to 0.2.13

renderer/src/features/chat/components/chat-interface.tsx, renderer/src/features/chat/components/dialog-api-keys.tsx, renderer/src/features/chat/components/mcp-server-settings.tsx, renderer/src/features/chat/components/mcp-tools-modal.tsx, renderer/src/features/chat/components/model-selector.tsx
I did a little bit of restyling and fine tuning
Also adjust the focus when you're searching a model
https://github.com/user-attachments/assets/95471f95-b20b-48c6-a592-a54bb5ece7b3
=> feat(playground): revisit empty state and fine tuning

main/src/chat/providers.ts
as per title, adding new model for Anthropic provider
=> feat(playground): add claude-sonnet-4-5 and revisit latest models for Anthropic provider

renderer/src/common/components/settings/registry/registry-type-field.tsx, renderer/src/common/components/workload-cmd-arg/command-arguments-field.tsx, renderer/src/features/mcp-servers/components/form-fields-array-custom-volumes.tsx, renderer/src/features/mcp-servers/components/network-isolation-tab-content.tsx, renderer/src/features/mcp-servers/components/remote-mcp/dialog-form-remote-mcp.tsx, renderer/src/features/mcp-servers/hooks/use-run-remote-server.tsx, renderer/src/features/mcp-servers/hooks/use-update-remote-server.tsx, renderer/src/features/network-isolation/components/network-isolation-tab-content.tsx, renderer/src/features/registry-servers/components/dialog-form-remote-registry-mcp.tsx, renderer/src/features/registry-servers/components/dynamic-array-field.tsx, renderer/src/features/registry-servers/components/form-run-from-registry/configuration-tab-content.tsx
Fix misalignments form fields for:
- custom local run mcp
- custom remote mcp
- edit custom local run mcp
- edit custom remote mcp 
- registry mcp
=> fix: form fields vertical alignments

renderer/src/common/components/title-page.tsx, renderer/src/routes/group.$groupName.tsx
as per title, very quick fix on the responsiveness of the title page component
https://github.com/user-attachments/assets/4b09ae3c-d98b-4106-8075-2d43146bb975
=> feat(title): response page title

renderer/src/features/mcp-servers/components/grid-cards-mcp-server.tsx, renderer/src/features/registry-servers/components/grid-cards-registry-server.tsx
just a POC based on this [PR](https://github.com/stacklok/toolhive-studio/pull/943) 
https://github.com/user-attachments/assets/b1ae619c-51ee-4a7d-98e6-c0f6ad743ba1
=> feat: make card layout more responsive v2

main/src/feature-flags.ts, renderer/src/common/components/layout/top-nav/index.tsx, utils/feature-flags.ts
In this PR we are removing the feature flag, making the `Playground` feature GA
=> feat(playground): ga removing feature flag

forge.config.ts, main/src/auto-update.ts, main/src/main.ts, main/src/menu.ts, main/src/system-tray.ts, main/src/tests/auto-update.test.ts, main/src/tests/toolhive-manager.test.ts, main/src/util.ts, main/src/utils/update-dialogs.ts, preload/src/preload.ts, renderer/src/common/components/layout/top-nav/index.tsx, renderer/src/common/components/settings/tabs/__tests__/settings-tabs.test.tsx, renderer/src/common/components/settings/tabs/__tests__/version-tab.test.tsx, renderer/src/common/components/settings/tabs/settings-tabs.tsx, renderer/src/common/components/settings/tabs/version-tab.tsx, renderer/src/common/hooks/use-app-version.ts, renderer/src/common/hooks/use-auto-update.ts, utils/fetch-thv.ts, utils/parse-release-version.ts
Added manual update functionality to the application UI and system tray, improving the user experience for managing application updates.
Next PRs:
- add tracing for the entire update flow
- reduce logs noice
**GitHub Pages Version Check**
Implemented `getLatestAvailableVersion()` function to check for new releases by:
- Fetching release metadata from `https://stacklok.github.io/toolhive-studio/latest`
- Filtering assets by current platform (darwin/win32/linux)
- Comparing the current app version with the latest available tag
- Returning version information with `isNewVersionAvailable` flag
**Settings UI**
Integrated update status and manual download controls in the Version tab:
- Displays update availability alerts with version information
- Shows "Download" button when a new version is …
=> feat: add manual app update
